// Code generated by woco, DO NOT EDIT.

package msg

import (
	"context"
	"errors"
	"io"
	"net/http"
)

type ReceiverAPI api

// (GET /receivers)
func (a *ReceiverAPI) GetReceivers(ctx context.Context) (ret []*Receiver, resp *http.Response, err error) {
	var (
		contentType string
		body        any
	)
	path := "/receivers"

	request, err := a.client.prepareRequest("GET", a.client.cfg.BasePath+path, contentType, body)
	if err != nil {
		return
	}
	accept := selectHeaderAccept([]string{"application/json"})
	request.Header.Set("Accept", accept)
	resp, err = a.client.Do(ctx, request)
	if err != nil {
		return
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	if resp.StatusCode == http.StatusOK {
		err = a.client.decode(respBody, &ret, resp.Header.Get("Content-Type"))
		if err == nil {
			return
		}
	} else if resp.StatusCode >= 300 {
		err = errors.New(string(respBody))
	}

	return
}
