// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HellosColumns holds the columns for the "hellos" table.
	HellosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeInt},
	}
	// HellosTable holds the schema information for the "hellos" table.
	HellosTable = &schema.Table{
		Name:       "hellos",
		Columns:    HellosColumns,
		PrimaryKey: []*schema.Column{HellosColumns[0]},
	}
	// WorldsColumns holds the columns for the "worlds" table.
	WorldsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "power_by", Type: field.TypeString, Nullable: true, Default: "0"},
	}
	// WorldsTable holds the schema information for the "worlds" table.
	WorldsTable = &schema.Table{
		Name:       "worlds",
		Columns:    WorldsColumns,
		PrimaryKey: []*schema.Column{WorldsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HellosTable,
		WorldsTable,
	}
)

func init() {
}
