// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RefTableColumns holds the columns for the "ref_table" table.
	RefTableColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// RefTableTable holds the schema information for the "ref_table" table.
	RefTableTable = &schema.Table{
		Name:       "ref_table",
		Columns:    RefTableColumns,
		PrimaryKey: []*schema.Column{RefTableColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 45},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "money", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"mysql": "decimal(10,6)", "postgres": "decimal(10,6)", "sqlite3": "decimal(10,6)"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RefTableTable,
		UsersTable,
	}
)

func init() {
	RefTableTable.Annotation = &entsql.Annotation{
		Table: "ref_table",
	}
}
