// Code generated by woco, DO NOT EDIT.

package file

import "time"

type Error struct {
	Code    int
	Details string
	Message string
}

type ErrorResponse struct {
	Errors []*Error
}

type FileInfo struct {
	FileSource *FileSource `json:"fileSource,omitempty"`
	CreatedAt  time.Time   `json:"createdAt,omitempty" time_format:"2006-01-02T15:04:05Z07:00"`
	ID         string      `json:"id,omitempty"`
	Name       string      `json:"name,omitempty"`
	Path       string      `json:"path,omitempty"`
	Size       int         `json:"size,omitempty"`
}

type FileInput struct {
	MineType string `binding:"required" json:"mine_type"`
	Name     string `binding:"required" json:"name"`
	Path     string `binding:"required" json:"path"`
	Size     int    `binding:"required" json:"size"`
}

type FileRefInput struct {
	FileId int `binding:"required" json:"fileId"`
	// OpType plus or minus the reference count
	OpType string `binding:"required" json:"opType"`
}

type FileSource struct {
	Bucket   string `json:"bucket,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	ID       int    `json:"id,omitempty"`
	Kind     string `json:"kind,omitempty"`
	Region   string `json:"region,omitempty"`
}

type FileSourceInput struct {
	Bucket   string `binding:"required" json:"bucket"`
	Endpoint string `binding:"required" json:"endpoint"`
	Kind     string `binding:"required" json:"kind"`
	Region   string `binding:"required" json:"region"`
}
