// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/woocoos/knockout-go/integration/gentest/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/woocoos/entcache"
	"github.com/woocoos/knockout-go/integration/gentest/ent/exgidschema"
	"github.com/woocoos/knockout-go/integration/gentest/ent/refschema"
	"github.com/woocoos/knockout-go/integration/gentest/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ExGIDSchema is the client for interacting with the ExGIDSchema builders.
	ExGIDSchema *ExGIDSchemaClient
	// RefSchema is the client for interacting with the RefSchema builders.
	RefSchema *RefSchemaClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// additional fields for node api
	tables tables
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ExGIDSchema = NewExGIDSchemaClient(c.config)
	c.RefSchema = NewRefSchemaClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		ExGIDSchema: NewExGIDSchemaClient(cfg),
		RefSchema:   NewRefSchemaClient(cfg),
		User:        NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		ExGIDSchema: NewExGIDSchemaClient(cfg),
		RefSchema:   NewRefSchemaClient(cfg),
		User:        NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ExGIDSchema.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ExGIDSchema.Use(hooks...)
	c.RefSchema.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ExGIDSchema.Intercept(interceptors...)
	c.RefSchema.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ExGIDSchemaMutation:
		return c.ExGIDSchema.mutate(ctx, m)
	case *RefSchemaMutation:
		return c.RefSchema.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ExGIDSchemaClient is a client for the ExGIDSchema schema.
type ExGIDSchemaClient struct {
	config
}

// NewExGIDSchemaClient returns a client for the ExGIDSchema from the given config.
func NewExGIDSchemaClient(c config) *ExGIDSchemaClient {
	return &ExGIDSchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `exgidschema.Hooks(f(g(h())))`.
func (c *ExGIDSchemaClient) Use(hooks ...Hook) {
	c.hooks.ExGIDSchema = append(c.hooks.ExGIDSchema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `exgidschema.Intercept(f(g(h())))`.
func (c *ExGIDSchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.ExGIDSchema = append(c.inters.ExGIDSchema, interceptors...)
}

// Create returns a builder for creating a ExGIDSchema entity.
func (c *ExGIDSchemaClient) Create() *ExGIDSchemaCreate {
	mutation := newExGIDSchemaMutation(c.config, OpCreate)
	return &ExGIDSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ExGIDSchema entities.
func (c *ExGIDSchemaClient) CreateBulk(builders ...*ExGIDSchemaCreate) *ExGIDSchemaCreateBulk {
	return &ExGIDSchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExGIDSchemaClient) MapCreateBulk(slice any, setFunc func(*ExGIDSchemaCreate, int)) *ExGIDSchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExGIDSchemaCreateBulk{err: fmt.Errorf("calling to ExGIDSchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExGIDSchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExGIDSchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ExGIDSchema.
func (c *ExGIDSchemaClient) Update() *ExGIDSchemaUpdate {
	mutation := newExGIDSchemaMutation(c.config, OpUpdate)
	return &ExGIDSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExGIDSchemaClient) UpdateOne(_m *ExGIDSchema) *ExGIDSchemaUpdateOne {
	mutation := newExGIDSchemaMutation(c.config, OpUpdateOne, withExGIDSchema(_m))
	return &ExGIDSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExGIDSchemaClient) UpdateOneID(id int) *ExGIDSchemaUpdateOne {
	mutation := newExGIDSchemaMutation(c.config, OpUpdateOne, withExGIDSchemaID(id))
	return &ExGIDSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ExGIDSchema.
func (c *ExGIDSchemaClient) Delete() *ExGIDSchemaDelete {
	mutation := newExGIDSchemaMutation(c.config, OpDelete)
	return &ExGIDSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExGIDSchemaClient) DeleteOne(_m *ExGIDSchema) *ExGIDSchemaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExGIDSchemaClient) DeleteOneID(id int) *ExGIDSchemaDeleteOne {
	builder := c.Delete().Where(exgidschema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExGIDSchemaDeleteOne{builder}
}

// Query returns a query builder for ExGIDSchema.
func (c *ExGIDSchemaClient) Query() *ExGIDSchemaQuery {
	return &ExGIDSchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExGIDSchema},
		inters: c.Interceptors(),
	}
}

// Get returns a ExGIDSchema entity by its id.
func (c *ExGIDSchemaClient) Get(ctx context.Context, id int) (*ExGIDSchema, error) {
	return c.Query().Where(exgidschema.ID(id)).Only(entcache.WithEntryKey(ctx, "ExGIDSchema", id))
}

// GetX is like Get, but panics if an error occurs.
func (c *ExGIDSchemaClient) GetX(ctx context.Context, id int) *ExGIDSchema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ExGIDSchemaClient) Hooks() []Hook {
	return c.hooks.ExGIDSchema
}

// Interceptors returns the client interceptors.
func (c *ExGIDSchemaClient) Interceptors() []Interceptor {
	return c.inters.ExGIDSchema
}

func (c *ExGIDSchemaClient) mutate(ctx context.Context, m *ExGIDSchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExGIDSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExGIDSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExGIDSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExGIDSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ExGIDSchema mutation op: %q", m.Op())
	}
}

// RefSchemaClient is a client for the RefSchema schema.
type RefSchemaClient struct {
	config
}

// NewRefSchemaClient returns a client for the RefSchema from the given config.
func NewRefSchemaClient(c config) *RefSchemaClient {
	return &RefSchemaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refschema.Hooks(f(g(h())))`.
func (c *RefSchemaClient) Use(hooks ...Hook) {
	c.hooks.RefSchema = append(c.hooks.RefSchema, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refschema.Intercept(f(g(h())))`.
func (c *RefSchemaClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefSchema = append(c.inters.RefSchema, interceptors...)
}

// Create returns a builder for creating a RefSchema entity.
func (c *RefSchemaClient) Create() *RefSchemaCreate {
	mutation := newRefSchemaMutation(c.config, OpCreate)
	return &RefSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefSchema entities.
func (c *RefSchemaClient) CreateBulk(builders ...*RefSchemaCreate) *RefSchemaCreateBulk {
	return &RefSchemaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefSchemaClient) MapCreateBulk(slice any, setFunc func(*RefSchemaCreate, int)) *RefSchemaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefSchemaCreateBulk{err: fmt.Errorf("calling to RefSchemaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefSchemaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefSchemaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefSchema.
func (c *RefSchemaClient) Update() *RefSchemaUpdate {
	mutation := newRefSchemaMutation(c.config, OpUpdate)
	return &RefSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefSchemaClient) UpdateOne(_m *RefSchema) *RefSchemaUpdateOne {
	mutation := newRefSchemaMutation(c.config, OpUpdateOne, withRefSchema(_m))
	return &RefSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefSchemaClient) UpdateOneID(id int) *RefSchemaUpdateOne {
	mutation := newRefSchemaMutation(c.config, OpUpdateOne, withRefSchemaID(id))
	return &RefSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefSchema.
func (c *RefSchemaClient) Delete() *RefSchemaDelete {
	mutation := newRefSchemaMutation(c.config, OpDelete)
	return &RefSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefSchemaClient) DeleteOne(_m *RefSchema) *RefSchemaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefSchemaClient) DeleteOneID(id int) *RefSchemaDeleteOne {
	builder := c.Delete().Where(refschema.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefSchemaDeleteOne{builder}
}

// Query returns a query builder for RefSchema.
func (c *RefSchemaClient) Query() *RefSchemaQuery {
	return &RefSchemaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefSchema},
		inters: c.Interceptors(),
	}
}

// Get returns a RefSchema entity by its id.
func (c *RefSchemaClient) Get(ctx context.Context, id int) (*RefSchema, error) {
	return c.Query().Where(refschema.ID(id)).Only(entcache.WithEntryKey(ctx, "RefSchema", id))
}

// GetX is like Get, but panics if an error occurs.
func (c *RefSchemaClient) GetX(ctx context.Context, id int) *RefSchema {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a RefSchema.
func (c *RefSchemaClient) QueryUser(_m *RefSchema) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(refschema.Table, refschema.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refschema.UserTable, refschema.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RefSchemaClient) Hooks() []Hook {
	return c.hooks.RefSchema
}

// Interceptors returns the client interceptors.
func (c *RefSchemaClient) Interceptors() []Interceptor {
	return c.inters.RefSchema
}

func (c *RefSchemaClient) mutate(ctx context.Context, m *RefSchemaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefSchemaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefSchemaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefSchemaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefSchemaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefSchema mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(entcache.WithEntryKey(ctx, "User", id))
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryRefs queries the refs edge of a User.
func (c *UserClient) QueryRefs(_m *User) *RefSchemaQuery {
	query := (&RefSchemaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(refschema.Table, refschema.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.RefsTable, user.RefsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	hooks := c.hooks.User
	return append(hooks[:len(hooks):len(hooks)], user.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ExGIDSchema, RefSchema, User []ent.Hook
	}
	inters struct {
		ExGIDSchema, RefSchema, User []ent.Interceptor
	}
)
