// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/gentest/ent/exgidschema"
	"github.com/woocoos/knockout-go/integration/gentest/ent/predicate"
)

// ExGIDSchemaDelete is the builder for deleting a ExGIDSchema entity.
type ExGIDSchemaDelete struct {
	config
	hooks    []Hook
	mutation *ExGIDSchemaMutation
}

// Where appends a list predicates to the ExGIDSchemaDelete builder.
func (_d *ExGIDSchemaDelete) Where(ps ...predicate.ExGIDSchema) *ExGIDSchemaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExGIDSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExGIDSchemaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExGIDSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(exgidschema.Table, sqlgraph.NewFieldSpec(exgidschema.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExGIDSchemaDeleteOne is the builder for deleting a single ExGIDSchema entity.
type ExGIDSchemaDeleteOne struct {
	_d *ExGIDSchemaDelete
}

// Where appends a list predicates to the ExGIDSchemaDelete builder.
func (_d *ExGIDSchemaDeleteOne) Where(ps ...predicate.ExGIDSchema) *ExGIDSchemaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExGIDSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{exgidschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExGIDSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
