// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/gentest/ent/predicate"
	"github.com/woocoos/knockout-go/integration/gentest/ent/refschema"
)

// RefSchemaQuery is the builder for querying RefSchema entities.
type RefSchemaQuery struct {
	config
	ctx        *QueryContext
	order      []refschema.OrderOption
	inters     []Interceptor
	predicates []predicate.RefSchema
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*RefSchema) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RefSchemaQuery builder.
func (rsq *RefSchemaQuery) Where(ps ...predicate.RefSchema) *RefSchemaQuery {
	rsq.predicates = append(rsq.predicates, ps...)
	return rsq
}

// Limit the number of records to be returned by this query.
func (rsq *RefSchemaQuery) Limit(limit int) *RefSchemaQuery {
	rsq.ctx.Limit = &limit
	return rsq
}

// Offset to start from.
func (rsq *RefSchemaQuery) Offset(offset int) *RefSchemaQuery {
	rsq.ctx.Offset = &offset
	return rsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rsq *RefSchemaQuery) Unique(unique bool) *RefSchemaQuery {
	rsq.ctx.Unique = &unique
	return rsq
}

// Order specifies how the records should be ordered.
func (rsq *RefSchemaQuery) Order(o ...refschema.OrderOption) *RefSchemaQuery {
	rsq.order = append(rsq.order, o...)
	return rsq
}

// First returns the first RefSchema entity from the query.
// Returns a *NotFoundError when no RefSchema was found.
func (rsq *RefSchemaQuery) First(ctx context.Context) (*RefSchema, error) {
	nodes, err := rsq.Limit(1).All(setContextOp(ctx, rsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{refschema.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rsq *RefSchemaQuery) FirstX(ctx context.Context) *RefSchema {
	node, err := rsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RefSchema ID from the query.
// Returns a *NotFoundError when no RefSchema ID was found.
func (rsq *RefSchemaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(1).IDs(setContextOp(ctx, rsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{refschema.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rsq *RefSchemaQuery) FirstIDX(ctx context.Context) int {
	id, err := rsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RefSchema entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RefSchema entity is found.
// Returns a *NotFoundError when no RefSchema entities are found.
func (rsq *RefSchemaQuery) Only(ctx context.Context) (*RefSchema, error) {
	nodes, err := rsq.Limit(2).All(setContextOp(ctx, rsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{refschema.Label}
	default:
		return nil, &NotSingularError{refschema.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rsq *RefSchemaQuery) OnlyX(ctx context.Context) *RefSchema {
	node, err := rsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RefSchema ID in the query.
// Returns a *NotSingularError when more than one RefSchema ID is found.
// Returns a *NotFoundError when no entities are found.
func (rsq *RefSchemaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rsq.Limit(2).IDs(setContextOp(ctx, rsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{refschema.Label}
	default:
		err = &NotSingularError{refschema.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rsq *RefSchemaQuery) OnlyIDX(ctx context.Context) int {
	id, err := rsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RefSchemas.
func (rsq *RefSchemaQuery) All(ctx context.Context) ([]*RefSchema, error) {
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryAll)
	if err := rsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RefSchema, *RefSchemaQuery]()
	return withInterceptors[[]*RefSchema](ctx, rsq, qr, rsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rsq *RefSchemaQuery) AllX(ctx context.Context) []*RefSchema {
	nodes, err := rsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RefSchema IDs.
func (rsq *RefSchemaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rsq.ctx.Unique == nil && rsq.path != nil {
		rsq.Unique(true)
	}
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryIDs)
	if err = rsq.Select(refschema.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rsq *RefSchemaQuery) IDsX(ctx context.Context) []int {
	ids, err := rsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rsq *RefSchemaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryCount)
	if err := rsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rsq, querierCount[*RefSchemaQuery](), rsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rsq *RefSchemaQuery) CountX(ctx context.Context) int {
	count, err := rsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rsq *RefSchemaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rsq.ctx, ent.OpQueryExist)
	switch _, err := rsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rsq *RefSchemaQuery) ExistX(ctx context.Context) bool {
	exist, err := rsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RefSchemaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rsq *RefSchemaQuery) Clone() *RefSchemaQuery {
	if rsq == nil {
		return nil
	}
	return &RefSchemaQuery{
		config:     rsq.config,
		ctx:        rsq.ctx.Clone(),
		order:      append([]refschema.OrderOption{}, rsq.order...),
		inters:     append([]Interceptor{}, rsq.inters...),
		predicates: append([]predicate.RefSchema{}, rsq.predicates...),
		// clone intermediate query.
		sql:  rsq.sql.Clone(),
		path: rsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RefSchema.Query().
//		GroupBy(refschema.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rsq *RefSchemaQuery) GroupBy(field string, fields ...string) *RefSchemaGroupBy {
	rsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RefSchemaGroupBy{build: rsq}
	grbuild.flds = &rsq.ctx.Fields
	grbuild.label = refschema.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.RefSchema.Query().
//		Select(refschema.FieldName).
//		Scan(ctx, &v)
func (rsq *RefSchemaQuery) Select(fields ...string) *RefSchemaSelect {
	rsq.ctx.Fields = append(rsq.ctx.Fields, fields...)
	sbuild := &RefSchemaSelect{RefSchemaQuery: rsq}
	sbuild.label = refschema.Label
	sbuild.flds, sbuild.scan = &rsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RefSchemaSelect configured with the given aggregations.
func (rsq *RefSchemaQuery) Aggregate(fns ...AggregateFunc) *RefSchemaSelect {
	return rsq.Select().Aggregate(fns...)
}

func (rsq *RefSchemaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rsq); err != nil {
				return err
			}
		}
	}
	for _, f := range rsq.ctx.Fields {
		if !refschema.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rsq.path != nil {
		prev, err := rsq.path(ctx)
		if err != nil {
			return err
		}
		rsq.sql = prev
	}
	return nil
}

func (rsq *RefSchemaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RefSchema, error) {
	var (
		nodes = []*RefSchema{}
		_spec = rsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RefSchema).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RefSchema{config: rsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(rsq.modifiers) > 0 {
		_spec.Modifiers = rsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range rsq.loadTotal {
		if err := rsq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rsq *RefSchemaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rsq.querySpec()
	if len(rsq.modifiers) > 0 {
		_spec.Modifiers = rsq.modifiers
	}
	_spec.Node.Columns = rsq.ctx.Fields
	if len(rsq.ctx.Fields) > 0 {
		_spec.Unique = rsq.ctx.Unique != nil && *rsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rsq.driver, _spec)
}

func (rsq *RefSchemaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(refschema.Table, refschema.Columns, sqlgraph.NewFieldSpec(refschema.FieldID, field.TypeInt))
	_spec.From = rsq.sql
	if unique := rsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rsq.path != nil {
		_spec.Unique = true
	}
	if fields := rsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refschema.FieldID)
		for i := range fields {
			if fields[i] != refschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rsq *RefSchemaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rsq.driver.Dialect())
	t1 := builder.Table(refschema.Table)
	columns := rsq.ctx.Fields
	if len(columns) == 0 {
		columns = refschema.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rsq.sql != nil {
		selector = rsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rsq.ctx.Unique != nil && *rsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rsq.predicates {
		p(selector)
	}
	for _, p := range rsq.order {
		p(selector)
	}
	if offset := rsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RefSchemaGroupBy is the group-by builder for RefSchema entities.
type RefSchemaGroupBy struct {
	selector
	build *RefSchemaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rsgb *RefSchemaGroupBy) Aggregate(fns ...AggregateFunc) *RefSchemaGroupBy {
	rsgb.fns = append(rsgb.fns, fns...)
	return rsgb
}

// Scan applies the selector query and scans the result into the given value.
func (rsgb *RefSchemaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rsgb.build.ctx, ent.OpQueryGroupBy)
	if err := rsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RefSchemaQuery, *RefSchemaGroupBy](ctx, rsgb.build, rsgb, rsgb.build.inters, v)
}

func (rsgb *RefSchemaGroupBy) sqlScan(ctx context.Context, root *RefSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rsgb.fns))
	for _, fn := range rsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rsgb.flds)+len(rsgb.fns))
		for _, f := range *rsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RefSchemaSelect is the builder for selecting fields of RefSchema entities.
type RefSchemaSelect struct {
	*RefSchemaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rss *RefSchemaSelect) Aggregate(fns ...AggregateFunc) *RefSchemaSelect {
	rss.fns = append(rss.fns, fns...)
	return rss
}

// Scan applies the selector query and scans the result into the given value.
func (rss *RefSchemaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rss.ctx, ent.OpQuerySelect)
	if err := rss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RefSchemaQuery, *RefSchemaSelect](ctx, rss.RefSchemaQuery, rss, rss.inters, v)
}

func (rss *RefSchemaSelect) sqlScan(ctx context.Context, root *RefSchemaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rss.fns))
	for _, fn := range rss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
