// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/gentest/ent/predicate"
	"github.com/woocoos/knockout-go/integration/gentest/ent/refschema"
	"github.com/woocoos/knockout-go/integration/gentest/ent/user"
)

// RefSchemaUpdate is the builder for updating RefSchema entities.
type RefSchemaUpdate struct {
	config
	hooks    []Hook
	mutation *RefSchemaMutation
}

// Where appends a list predicates to the RefSchemaUpdate builder.
func (_u *RefSchemaUpdate) Where(ps ...predicate.RefSchema) *RefSchemaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RefSchemaUpdate) SetName(v string) *RefSchemaUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RefSchemaUpdate) SetNillableName(v *string) *RefSchemaUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RefSchemaUpdate) SetUserID(v int) *RefSchemaUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RefSchemaUpdate) SetNillableUserID(v *int) *RefSchemaUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RefSchemaUpdate) SetUser(v *User) *RefSchemaUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RefSchemaMutation object of the builder.
func (_u *RefSchemaUpdate) Mutation() *RefSchemaMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RefSchemaUpdate) ClearUser() *RefSchemaUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RefSchemaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RefSchemaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RefSchemaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RefSchemaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RefSchemaUpdate) check() error {
	if _, ok := _u.mutation.UserID(); _u.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "RefSchema.user"`)
	}
	return nil
}

func (_u *RefSchemaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refschema.Table, refschema.Columns, sqlgraph.NewFieldSpec(refschema.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(refschema.FieldName, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refschema.UserTable,
			Columns: []string{refschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refschema.UserTable,
			Columns: []string{refschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RefSchemaUpdateOne is the builder for updating a single RefSchema entity.
type RefSchemaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RefSchemaMutation
}

// SetName sets the "name" field.
func (rsuo *RefSchemaUpdateOne) SetName(v string) *RefSchemaUpdateOne {
	rsuo.mutation.SetName(v)
	return rsuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (rsuo *RefSchemaUpdateOne) SetNillableName(v *string) *RefSchemaUpdateOne {
	if v != nil {
		rsuo.SetName(*v)
	}
	return rsuo
}

// SetUserID sets the "user_id" field.
func (rsuo *RefSchemaUpdateOne) SetUserID(v int) *RefSchemaUpdateOne {
	rsuo.mutation.SetUserID(v)
	return rsuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (rsuo *RefSchemaUpdateOne) SetNillableUserID(v *int) *RefSchemaUpdateOne {
	if v != nil {
		rsuo.SetUserID(*v)
	}
	return rsuo
}

// SetUser sets the "user" edge to the User entity.
func (rsuo *RefSchemaUpdateOne) SetUser(v *User) *RefSchemaUpdateOne {
	return rsuo.SetUserID(v.ID)
}

// Mutation returns the RefSchemaMutation object of the builder.
func (rsuo *RefSchemaUpdateOne) Mutation() *RefSchemaMutation {
	return rsuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (rsuo *RefSchemaUpdateOne) ClearUser() *RefSchemaUpdateOne {
	rsuo.mutation.ClearUser()
	return rsuo
}

// Where appends a list predicates to the RefSchemaUpdate builder.
func (rsuo *RefSchemaUpdateOne) Where(ps ...predicate.RefSchema) *RefSchemaUpdateOne {
	rsuo.mutation.Where(ps...)
	return rsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rsuo *RefSchemaUpdateOne) Select(field string, fields ...string) *RefSchemaUpdateOne {
	rsuo.fields = append([]string{field}, fields...)
	return rsuo
}

// Save executes the query and returns the updated RefSchema entity.
func (rsuo *RefSchemaUpdateOne) Save(ctx context.Context) (*RefSchema, error) {
	return withHooks(ctx, rsuo.sqlSave, rsuo.mutation, rsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rsuo *RefSchemaUpdateOne) SaveX(ctx context.Context) *RefSchema {
	node, err := rsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rsuo *RefSchemaUpdateOne) Exec(ctx context.Context) error {
	_, err := rsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsuo *RefSchemaUpdateOne) ExecX(ctx context.Context) {
	if err := rsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rsuo *RefSchemaUpdateOne) check() error {
	if _, ok := rsuo.mutation.UserID(); rsuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "RefSchema.user"`)
	}
	return nil
}

func (rsuo *RefSchemaUpdateOne) sqlSave(ctx context.Context) (_node *RefSchema, err error) {
	if err := rsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(refschema.Table, refschema.Columns, sqlgraph.NewFieldSpec(refschema.FieldID, field.TypeInt))
	id, ok := rsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RefSchema.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, refschema.FieldID)
		for _, f := range fields {
			if !refschema.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != refschema.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rsuo.mutation.Name(); ok {
		_spec.SetField(refschema.FieldName, field.TypeString, value)
	}
	if rsuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refschema.UserTable,
			Columns: []string{refschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := rsuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   refschema.UserTable,
			Columns: []string{refschema.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RefSchema{config: rsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{refschema.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rsuo.mutation.done = true
	return _node, nil
}
