// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/gentest/ent/predicate"
	"github.com/woocoos/knockout-go/integration/gentest/ent/refschema"
)

// RefSchemaDelete is the builder for deleting a RefSchema entity.
type RefSchemaDelete struct {
	config
	hooks    []Hook
	mutation *RefSchemaMutation
}

// Where appends a list predicates to the RefSchemaDelete builder.
func (_d *RefSchemaDelete) Where(ps ...predicate.RefSchema) *RefSchemaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RefSchemaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RefSchemaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RefSchemaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(refschema.Table, sqlgraph.NewFieldSpec(refschema.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RefSchemaDeleteOne is the builder for deleting a single RefSchema entity.
type RefSchemaDeleteOne struct {
	_d *RefSchemaDelete
}

// Where appends a list predicates to the RefSchemaDelete builder.
func (_d *RefSchemaDeleteOne) Where(ps ...predicate.RefSchema) *RefSchemaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RefSchemaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{refschema.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RefSchemaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
