// Code generated by woco, DO NOT EDIT.

package auth

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strconv"
)

type AuthAPI api

// (GET /org/domain)
func (a *AuthAPI) GetDomain(ctx context.Context, req *GetDomainRequest) (ret *Domain, resp *http.Response, err error) {
	var (
		contentType string
		body        any
	)
	path := "/org/domain"
	queryParams := url.Values{}
	queryParams.Add("orgID", strconv.FormatInt(int64(req.OrgID), 10))

	request, err := a.client.prepareRequest("GET", a.client.cfg.BasePath+path, contentType, body)
	if err != nil {
		return
	}
	request.URL.RawQuery = queryParams.Encode()
	accept := selectHeaderAccept([]string{"application/json"})
	request.Header.Set("Accept", accept)
	resp, err = a.client.Do(ctx, request)
	if err != nil {
		return
	}
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return
	}
	if resp.StatusCode == http.StatusOK {
		ret = new(Domain)
		err = a.client.decode(respBody, ret, resp.Header.Get("Content-Type"))
		if err == nil {
			return
		}
	} else if resp.StatusCode >= 300 {
		err = errors.New(string(respBody))
	}

	return
}
