// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/nocache/ent/nocache"
	"github.com/woocoos/knockout-go/integration/nocache/ent/predicate"
)

// NoCacheDelete is the builder for deleting a NoCache entity.
type NoCacheDelete struct {
	config
	hooks    []Hook
	mutation *NoCacheMutation
}

// Where appends a list predicates to the NoCacheDelete builder.
func (ncd *NoCacheDelete) Where(ps ...predicate.NoCache) *NoCacheDelete {
	ncd.mutation.Where(ps...)
	return ncd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ncd *NoCacheDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ncd.sqlExec, ncd.mutation, ncd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ncd *NoCacheDelete) ExecX(ctx context.Context) int {
	n, err := ncd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ncd *NoCacheDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nocache.Table, sqlgraph.NewFieldSpec(nocache.FieldID, field.TypeInt))
	if ps := ncd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ncd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ncd.mutation.done = true
	return affected, err
}

// NoCacheDeleteOne is the builder for deleting a single NoCache entity.
type NoCacheDeleteOne struct {
	ncd *NoCacheDelete
}

// Where appends a list predicates to the NoCacheDelete builder.
func (ncdo *NoCacheDeleteOne) Where(ps ...predicate.NoCache) *NoCacheDeleteOne {
	ncdo.ncd.mutation.Where(ps...)
	return ncdo
}

// Exec executes the deletion query.
func (ncdo *NoCacheDeleteOne) Exec(ctx context.Context) error {
	n, err := ncdo.ncd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nocache.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ncdo *NoCacheDeleteOne) ExecX(ctx context.Context) {
	if err := ncdo.Exec(ctx); err != nil {
		panic(err)
	}
}
