// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/nocache/ent/nocache"
	"github.com/woocoos/knockout-go/integration/nocache/ent/predicate"
)

// NoCacheUpdate is the builder for updating NoCache entities.
type NoCacheUpdate struct {
	config
	hooks    []Hook
	mutation *NoCacheMutation
}

// Where appends a list predicates to the NoCacheUpdate builder.
func (_u *NoCacheUpdate) Where(ps ...predicate.NoCache) *NoCacheUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NoCacheUpdate) SetName(v string) *NoCacheUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NoCacheUpdate) SetNillableName(v *string) *NoCacheUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NoCacheUpdate) SetUserID(v int) *NoCacheUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NoCacheUpdate) SetNillableUserID(v *int) *NoCacheUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NoCacheUpdate) AddUserID(v int) *NoCacheUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the NoCacheMutation object of the builder.
func (_u *NoCacheUpdate) Mutation() *NoCacheMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NoCacheUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NoCacheUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NoCacheUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NoCacheUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NoCacheUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(nocache.Table, nocache.Columns, sqlgraph.NewFieldSpec(nocache.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(nocache.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(nocache.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(nocache.FieldUserID, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nocache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NoCacheUpdateOne is the builder for updating a single NoCache entity.
type NoCacheUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NoCacheMutation
}

// SetName sets the "name" field.
func (ncuo *NoCacheUpdateOne) SetName(v string) *NoCacheUpdateOne {
	ncuo.mutation.SetName(v)
	return ncuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ncuo *NoCacheUpdateOne) SetNillableName(v *string) *NoCacheUpdateOne {
	if v != nil {
		ncuo.SetName(*v)
	}
	return ncuo
}

// SetUserID sets the "user_id" field.
func (ncuo *NoCacheUpdateOne) SetUserID(v int) *NoCacheUpdateOne {
	ncuo.mutation.ResetUserID()
	ncuo.mutation.SetUserID(v)
	return ncuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ncuo *NoCacheUpdateOne) SetNillableUserID(v *int) *NoCacheUpdateOne {
	if v != nil {
		ncuo.SetUserID(*v)
	}
	return ncuo
}

// AddUserID adds value to the "user_id" field.
func (ncuo *NoCacheUpdateOne) AddUserID(v int) *NoCacheUpdateOne {
	ncuo.mutation.AddUserID(v)
	return ncuo
}

// Mutation returns the NoCacheMutation object of the builder.
func (ncuo *NoCacheUpdateOne) Mutation() *NoCacheMutation {
	return ncuo.mutation
}

// Where appends a list predicates to the NoCacheUpdate builder.
func (ncuo *NoCacheUpdateOne) Where(ps ...predicate.NoCache) *NoCacheUpdateOne {
	ncuo.mutation.Where(ps...)
	return ncuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ncuo *NoCacheUpdateOne) Select(field string, fields ...string) *NoCacheUpdateOne {
	ncuo.fields = append([]string{field}, fields...)
	return ncuo
}

// Save executes the query and returns the updated NoCache entity.
func (ncuo *NoCacheUpdateOne) Save(ctx context.Context) (*NoCache, error) {
	return withHooks(ctx, ncuo.sqlSave, ncuo.mutation, ncuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ncuo *NoCacheUpdateOne) SaveX(ctx context.Context) *NoCache {
	node, err := ncuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ncuo *NoCacheUpdateOne) Exec(ctx context.Context) error {
	_, err := ncuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncuo *NoCacheUpdateOne) ExecX(ctx context.Context) {
	if err := ncuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ncuo *NoCacheUpdateOne) sqlSave(ctx context.Context) (_node *NoCache, err error) {
	_spec := sqlgraph.NewUpdateSpec(nocache.Table, nocache.Columns, sqlgraph.NewFieldSpec(nocache.FieldID, field.TypeInt))
	id, ok := ncuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NoCache.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ncuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nocache.FieldID)
		for _, f := range fields {
			if !nocache.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != nocache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ncuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ncuo.mutation.Name(); ok {
		_spec.SetField(nocache.FieldName, field.TypeString, value)
	}
	if value, ok := ncuo.mutation.UserID(); ok {
		_spec.SetField(nocache.FieldUserID, field.TypeInt, value)
	}
	if value, ok := ncuo.mutation.AddedUserID(); ok {
		_spec.AddField(nocache.FieldUserID, field.TypeInt, value)
	}
	_node = &NoCache{config: ncuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ncuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nocache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ncuo.mutation.done = true
	return _node, nil
}
