// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// NoCachesColumns holds the columns for the "no_caches" table.
	NoCachesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt},
	}
	// NoCachesTable holds the schema information for the "no_caches" table.
	NoCachesTable = &schema.Table{
		Name:       "no_caches",
		Columns:    NoCachesColumns,
		PrimaryKey: []*schema.Column{NoCachesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		NoCachesTable,
	}
)

func init() {
}
