// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/knockout-go/integration/helloapp/ent/predicate"
	"github.com/woocoos/knockout-go/integration/helloapp/ent/world"
)

// WorldUpdate is the builder for updating World entities.
type WorldUpdate struct {
	config
	hooks    []Hook
	mutation *WorldMutation
}

// Where appends a list predicates to the WorldUpdate builder.
func (_u *WorldUpdate) Where(ps ...predicate.World) *WorldUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *WorldUpdate) SetUpdatedBy(v int) *WorldUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *WorldUpdate) SetNillableUpdatedBy(v *int) *WorldUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *WorldUpdate) AddUpdatedBy(v int) *WorldUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *WorldUpdate) ClearUpdatedBy() *WorldUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorldUpdate) SetUpdatedAt(v time.Time) *WorldUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorldUpdate) SetNillableUpdatedAt(v *time.Time) *WorldUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WorldUpdate) ClearUpdatedAt() *WorldUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorldUpdate) SetDeletedAt(v time.Time) *WorldUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorldUpdate) SetNillableDeletedAt(v *time.Time) *WorldUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorldUpdate) ClearDeletedAt() *WorldUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *WorldUpdate) SetName(v string) *WorldUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorldUpdate) SetNillableName(v *string) *WorldUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPowerBy sets the "power_by" field.
func (_u *WorldUpdate) SetPowerBy(v string) *WorldUpdate {
	_u.mutation.SetPowerBy(v)
	return _u
}

// SetNillablePowerBy sets the "power_by" field if the given value is not nil.
func (_u *WorldUpdate) SetNillablePowerBy(v *string) *WorldUpdate {
	if v != nil {
		_u.SetPowerBy(*v)
	}
	return _u
}

// ClearPowerBy clears the value of the "power_by" field.
func (_u *WorldUpdate) ClearPowerBy() *WorldUpdate {
	_u.mutation.ClearPowerBy()
	return _u
}

// Mutation returns the WorldMutation object of the builder.
func (_u *WorldUpdate) Mutation() *WorldMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorldUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorldUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorldUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorldUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorldUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(world.Table, world.Columns, sqlgraph.NewFieldSpec(world.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(world.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(world.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(world.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(world.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(world.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(world.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(world.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(world.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PowerBy(); ok {
		_spec.SetField(world.FieldPowerBy, field.TypeString, value)
	}
	if _u.mutation.PowerByCleared() {
		_spec.ClearField(world.FieldPowerBy, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{world.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorldUpdateOne is the builder for updating a single World entity.
type WorldUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorldMutation
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *WorldUpdateOne) SetUpdatedBy(v int) *WorldUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *WorldUpdateOne) SetNillableUpdatedBy(v *int) *WorldUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *WorldUpdateOne) AddUpdatedBy(v int) *WorldUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *WorldUpdateOne) ClearUpdatedBy() *WorldUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorldUpdateOne) SetUpdatedAt(v time.Time) *WorldUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WorldUpdateOne) SetNillableUpdatedAt(v *time.Time) *WorldUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WorldUpdateOne) ClearUpdatedAt() *WorldUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *WorldUpdateOne) SetDeletedAt(v time.Time) *WorldUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *WorldUpdateOne) SetNillableDeletedAt(v *time.Time) *WorldUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *WorldUpdateOne) ClearDeletedAt() *WorldUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *WorldUpdateOne) SetName(v string) *WorldUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorldUpdateOne) SetNillableName(v *string) *WorldUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPowerBy sets the "power_by" field.
func (_u *WorldUpdateOne) SetPowerBy(v string) *WorldUpdateOne {
	_u.mutation.SetPowerBy(v)
	return _u
}

// SetNillablePowerBy sets the "power_by" field if the given value is not nil.
func (_u *WorldUpdateOne) SetNillablePowerBy(v *string) *WorldUpdateOne {
	if v != nil {
		_u.SetPowerBy(*v)
	}
	return _u
}

// ClearPowerBy clears the value of the "power_by" field.
func (_u *WorldUpdateOne) ClearPowerBy() *WorldUpdateOne {
	_u.mutation.ClearPowerBy()
	return _u
}

// Mutation returns the WorldMutation object of the builder.
func (_u *WorldUpdateOne) Mutation() *WorldMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorldUpdate builder.
func (_u *WorldUpdateOne) Where(ps ...predicate.World) *WorldUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorldUpdateOne) Select(field string, fields ...string) *WorldUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated World entity.
func (_u *WorldUpdateOne) Save(ctx context.Context) (*World, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorldUpdateOne) SaveX(ctx context.Context) *World {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorldUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorldUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WorldUpdateOne) sqlSave(ctx context.Context) (_node *World, err error) {
	_spec := sqlgraph.NewUpdateSpec(world.Table, world.Columns, sqlgraph.NewFieldSpec(world.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "World.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, world.FieldID)
		for _, f := range fields {
			if !world.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != world.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(world.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(world.FieldUpdatedBy, field.TypeInt, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(world.FieldUpdatedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(world.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(world.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(world.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(world.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(world.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PowerBy(); ok {
		_spec.SetField(world.FieldPowerBy, field.TypeString, value)
	}
	if _u.mutation.PowerByCleared() {
		_spec.ClearField(world.FieldPowerBy, field.TypeString)
	}
	_node = &World{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{world.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
